### ISSUE TITLE
Write conclusions / recommendations section of report

### ISSUE THREAD

**Issue by YingzhuoYang** [JerryWuZiJie/go_to_bed#22]
Discuss your design. What challenges did you face? What are your recommendations for future iterations?

Please address:

apply engineering design to produce solutions that meet specified needs with consideration of public health, safety, & welfare, as well as global, cultural, social, environmental, & economic factors
recognize ethical & professional responsibilities in engineering situations & make informed judgments, which consider the impact of engineering solutions in global, economic, environmental, & societal contexts

As Appendix I, include your demo video and pitch video.

**Comment by JerryWuZiJie** [comment]
done
