### ISSUE TITLE
Write LED demo.py

### ISSUE THREAD

**Issue by JerryWuZiJie** [JerryWuZiJie/go_to_bed#24]
@YingzhuoYang 

- [ ] fill in all needed functionality
- [ ] fill in stub functions

**Comment by YingzhuoYang** [comment]
[DSAZIHA2X000148723.pdf](https://github.com/JerryWuZiJie/go_to_bed/files/8082176/DSAZIHA2X000148723.pdf)
[1001datasheet.pdf](https://github.com/JerryWuZiJie/go_to_bed/files/8082177/1001datasheet.pdf)

**Comment by YingzhuoYang** [comment]
[max7219-max7221-1178406.pdf](https://github.com/JerryWuZiJie/go_to_bed/files/8121546/max7219-max7221-1178406.pdf)
[DSAZIHA2X000148723.pdf](https://github.com/JerryWuZiJie/go_to_bed/files/8121547/DSAZIHA2X000148723.pdf)

**Comment by YingzhuoYang** [comment]
import RPi.GPIO as GPIO

import time

SDI = 10

RCLK = 8

SRCLK = 11

CLK_TIME = 0.05

def setup():

  GPIO.setwarnings(False)

  GPIO.setmode(GPIO.BCM)

# BCM pin numbering

  GPIO.setup(SDI, GPIO.OUT)

  GPIO.setup(RCLK, GPIO.OUT)

  GPIO.setup(SRCLK, GPIO.OUT)

  GPIO.output(SDI, GPIO.LOW)

  GPIO.output(RCLK, GPIO.LOW)

  GPIO.output(SRCLK, GPIO.LOW)

def pulse_clk(clk):

  GPIO.output(clk, GPIO.LOW)

  time.sleep(CLK_TIME)

  GPIO.output(clk, GPIO.HIGH)

  time.sleep(CLK_TIME)

def send_byte(byte):

  GPIO.output(SDI,GPIO.LOW)

  GPIO.output(RCLK,GPIO.LOW)

  bitarray = [int(b) for b in format(byte, '08b')]

  for bit in bitarray:

    GPIO.output(SDI, bit)

    pulse_clk(SRCLK)

  pulse_clk(RCLK)

  GPIO.output(RCLK,GPIO.HIGH)
  
  GPIO.output(SDI,GPIO.LOW)

if __name__ == '__main__':

  setup()

  send_byte(0b1111111111111111)


  time.sleep(10)
  

  GPIO.cleanup()

**Comment by YingzhuoYang** [comment]
43dd4a16dec9b4ff96bc3efa272cfa72746b59d5

**Comment by JerryWuZiJie** [comment]
Going to modify the demo

**Comment by JerryWuZiJie** [comment]
5b1ed183028af41d24f1cae14d3e2fe4159bee55
