### ISSUE TITLE
Check part "liveness" (LED)

### ISSUE THREAD

**Issue by JerryWuZiJie** [JerryWuZiJie/go_to_bed#28]
@YingzhuoYang 
Make sure the part works as expected

**Comment by YingzhuoYang** [comment]
I used the data sheet to connect the LED pin to ground and tested each digital pin ABCDEFG and they all light up properly. 
![IMG_5323](https://user-images.githubusercontent.com/98344909/154333383-ebd0df23-a570-4cf5-a227-9f778264548a.jpeg)
