### ISSUE TITLE
Set up repository on Github

### ISSUE THREAD

**Issue by YingzhuoYang** [JerryWuZiJie/go_to_bed#3]
- [x] Create repository
- [x] Add collaborators
- [x] Set up Milestones
- [x] Set up Labels
- [x] Associate with Project

**Comment by YingzhuoYang** [comment]
"easy", "medium", "hard" are for difficulty levels.
"software", "testing", "hardware", "design", "documentation" are for types of tasks. 
"bug" is for when something is not  working. 
"duplicate" is for when it's already exist. 
"enhancement" is when there is new feature or request. 
"help wanted" is when it need extra attention. 
"invalid" is when something went wrong. 
"question" is when further information is requested.
"wont fix" is when this will not be worked on.

**Comment by JerryWuZiJie** [comment]
Everything in this issue is checked

**Comment by YingzhuoYang** [comment]
@ffund Please review our project!
