### ISSUE TITLE
Project specific tests (LED)

### ISSUE THREAD

**Issue by JerryWuZiJie** [JerryWuZiJie/go_to_bed#31]
@YingzhuoYang

**Comment by YingzhuoYang** [comment]
[DSAZIHA2X000148723.pdf](https://github.com/JerryWuZiJie/go_to_bed/files/8082173/DSAZIHA2X000148723.pdf)
[1001datasheet.pdf](https://github.com/JerryWuZiJie/go_to_bed/files/8082174/1001datasheet.pdf)

**Comment by YingzhuoYang** [comment]
[max7219-max7221-1178406.pdf](https://github.com/JerryWuZiJie/go_to_bed/files/8121548/max7219-max7221-1178406.pdf)
[DSAZIHA2X000148723.pdf](https://github.com/JerryWuZiJie/go_to_bed/files/8121549/DSAZIHA2X000148723.pdf)

**Comment by JerryWuZiJie** [comment]
Take over from @YingzhuoYang

**Comment by JerryWuZiJie** [comment]
5b1ed183028af41d24f1cae14d3e2fe4159bee55
