### ISSUE TITLE
Check part "liveness" (speaker)

### ISSUE THREAD

**Issue by JerryWuZiJie** [JerryWuZiJie/go_to_bed#32]
@JerryWuZiJie 

- [ ] make sure the speaker can generate sound
- [ ] test the speaker amplifier

**Comment by JerryWuZiJie** [comment]
When testing with speak, I follow the [instruction](https://learn.adafruit.com/adafruit-max98357-i2s-class-d-mono-amp/raspberry-pi-usage) to download all requirements. I'm able to run "alsamixer", but when I tried to play sound using the demo script, nothing is coming out from the speaker.
I check the voltage on the output, and there's zero voltage when sound is played. Possible reasons could be

1. the multimeter is not able to measure the voltage that changes very fast (in this case 300KHz)
2. the software and driver didn't install correctly on raspberry pi zero
3. the hardware wire connections are incorrect

I'll need to further investigate the issue and talk to the professor.
For now, I have written some setup instructions for the [MAX98357 I2S Amp](https://learn.adafruit.com/adafruit-max98357-i2s-class-d-mono-amp) locally and would upload to google drive once done

**Comment by JerryWuZiJie** [comment]
I use the following steps to setup the connection:

1. connect pi through ssh
2. hardware wiring:
    1. Amp Vin to Raspberry Pi 5V
    2. Amp GND to Raspberry Pi GND 
    3. Amp DIN to Raspberry Pi GPIO 21 
    4. Amp BCLK to Raspberry Pi GPIO 18 
    5. Amp LRCLK to Raspberry Pi GPIO 19
    6. speaker to the terminal block
    ![798e114f0c9b9143207cc34855299a9](https://user-images.githubusercontent.com/60801098/154326918-fea78d97-71f4-4d5f-92cc-7d834344edd6.jpg)
    ![cf9142424e73bad14490f5cbd4b2c2c](https://user-images.githubusercontent.com/60801098/154327100-93cc9768-6458-48b2-aeec-3a0491637bb3.jpg)
    ![7f44ee79424cfd73efa71cde5ba8d06](https://user-images.githubusercontent.com/60801098/154327122-1a2f4f1d-9f50-4a45-8371-aa9578f777af.jpg)
3. run script using "curl -sS https://raw.githubusercontent.com/adafruit/Raspberry-Pi-Installer-Scripts/master/i2samp.sh | bash" in pi terminal
4. type "y" for all prompts except for "Activate 'dev/zero/'...", choosing y might cause the speaker muted (it doesn't work for me, but you could give it a try). The last prompt will ask to reboot the pi
5. after reboot, run the same script again, and it will ask if you want to test the speaker. Type yes and see if the sound is coming out
6. reboot again and type the command "alsamixer" which enables you to control the volume

**Comment by JerryWuZiJie** [comment]
@YingzhuoYang please review

**Comment by ffund** [comment]
@JerryWuZiJie Following up on this, because you asked me about it in the lab session. I see that the issue is now closed and in Review status, does that mean that you resolved the problem you were having and completed the issue?

**Comment by JerryWuZiJie** [comment]
@ffund Yes, sorry to I forget to mention to you but I manage to get it working eventually

**Comment by JerryWuZiJie** [comment]
@ffund The problem is for a certain command ("Activate 'dev/zero/'...") I need to choose no even yes is recommended, I have recorded that in the [comment](https://github.com/JerryWuZiJie/go_to_bed/issues/32#issuecomment-1041970403) and will have a more detailed description in the report
