### ISSUE TITLE
Review design with respect to basic UX principles

### ISSUE THREAD

**Issue by JerryWuZiJie** [JerryWuZiJie/go_to_bed#37]

**Comment by YingzhuoYang** [comment]
Based on feedback from end users, we made the following changes to the product design:
Buttons have been added to the top of the device to make it easier for users to switch on and off and set alarms
Added local time setting and view other user information in user interface
Increased the ability for one person to use this device

For end-user feedback, please refer to the User Experience(UX) section of the report
https://docs.google.com/document/d/1cRgLtwa4frtZ_yciSRpZw53O9PJ7il5CS3-KFaFuV6g/edit#
