### ISSUE TITLE
Schematic for physical UI

### ISSUE THREAD

**Issue by JerryWuZiJie** [JerryWuZiJie/go_to_bed#4]
Some parts changed, so the circuit need to be modified

- [ ] 4 bits 7-segment LED with driver
- [ ] speaker with amplifier
- [ ] light sensor with ADC

**Comment by YingzhuoYang** [comment]
[Physical UI Schematic.pdf](https://github.com/JerryWuZiJie/go_to_bed/files/8567281/Physical.UI.Schematic.pdf)

**Comment by YingzhuoYang** [comment]
[Physical UI Schematic.pdf](https://github.com/JerryWuZiJie/go_to_bed/files/8567339/Physical.UI.Schematic.pdf)

**Comment by YingzhuoYang** [comment]
[Schematic.pdf](https://github.com/JerryWuZiJie/go_to_bed/files/8586184/Schematic.pdf)

**Comment by YingzhuoYang** [comment]
[Physical UI Schematic.pdf](https://github.com/JerryWuZiJie/go_to_bed/files/8646027/Physical.UI.Schematic.pdf)

**Comment by YingzhuoYang** [comment]
[Schematic for physical UI.zip](https://github.com/JerryWuZiJie/go_to_bed/files/8646109/Schematic.for.physical.UI.zip)
