### ISSUE TITLE
compile user research for personas

### ISSUE THREAD

**Issue by JerryWuZiJie** [JerryWuZiJie/go_to_bed#41]

**Comment by YingzhuoYang** [comment]
<img width="1557" alt="Screen Shot 2022-03-06 at 14 57 42" src="https://user-images.githubusercontent.com/98344909/156939907-05c68022-85e2-47c5-b1c4-1e328d21df3e.png">

**Comment by YingzhuoYang** [comment]
<img width="1231" alt="Screen Shot 2022-03-27 at 22 55 09" src="https://user-images.githubusercontent.com/98344909/160318808-5051aa7e-2f6e-494f-b470-ae65ef1925a2.png">

**Comment by YingzhuoYang** [comment]
<img width="1247" alt="Screen Shot 2022-04-27 at 13 25 18" src="https://user-images.githubusercontent.com/98344909/165584373-0cca5c5f-da65-4852-bf03-f9f9acedb05b.png">
