### ISSUE TITLE
create affinity map

### ISSUE THREAD

**Issue by JerryWuZiJie** [JerryWuZiJie/go_to_bed#42]
check [this](https://jamboard.google.com/d/1n-aOYw-6_pLYVfINGHePzV2yy6hOEUYMmje8X_mQ0rY/viewer?f=0)

**Comment by YingzhuoYang** [comment]
<img width="1557" alt="Screen Shot 2022-03-06 at 14 57 49" src="https://user-images.githubusercontent.com/98344909/156939925-d290acf6-0d66-4cfa-aa96-d26865d0ce27.png">

**Comment by YingzhuoYang** [comment]
Affinity map revision 
<img width="1553" alt="Screen Shot 2022-03-09 at 12 20 19" src="https://user-images.githubusercontent.com/98344909/157495975-de78099f-5a8a-468d-a329-9e4f7353b422.png">

**Comment by YingzhuoYang** [comment]
<img width="1231" alt="Screen Shot 2022-03-27 at 22 55 20" src="https://user-images.githubusercontent.com/98344909/160318894-fd3f3dd0-663b-4d30-b214-450149920ca7.png">

**Comment by YingzhuoYang** [comment]
<img width="1189" alt="Screen Shot 2022-04-20 at 13 03 47" src="https://user-images.githubusercontent.com/98344909/164284697-bfecf59b-d309-453e-9c7d-915784b44d8a.png">

**Comment by YingzhuoYang** [comment]
<img width="1216" alt="Screen Shot 2022-04-27 at 13 24 47" src="https://user-images.githubusercontent.com/98344909/165584264-3ac919f5-cf6a-440b-980c-062c6cef9f7a.png">
