### ISSUE TITLE
create personas

### ISSUE THREAD

**Issue by JerryWuZiJie** [JerryWuZiJie/go_to_bed#43]
at least 3 personas, check [this](https://jamboard.google.com/d/1n-aOYw-6_pLYVfINGHePzV2yy6hOEUYMmje8X_mQ0rY/viewer?f=3)

**Comment by YingzhuoYang** [comment]
<img width="1557" alt="Screen Shot 2022-03-06 at 14 57 58" src="https://user-images.githubusercontent.com/98344909/156939940-8ab94ca0-7008-4a73-b0a2-e22911ea53f0.png">
<img width="1557" alt="Screen Shot 2022-03-06 at 14 57 55" src="https://user-images.githubusercontent.com/98344909/156939941-bf1c8a25-d038-4c45-b87a-9b65f2463301.png">
<img width="1557" alt="Screen Shot 2022-03-06 at 14 57 52" src="https://user-images.githubusercontent.com/98344909/156939942-79c78c3a-a0c6-4fc5-9532-e672d7fd7620.png">

**Comment by YingzhuoYang** [comment]
<img width="1557" alt="Screen Shot 2022-03-06 at 14 59 37" src="https://user-images.githubusercontent.com/98344909/156939982-db43a585-83af-4a0f-87a6-dc3f6e51a875.png">
<img width="1557" alt="Screen Shot 2022-03-06 at 14 59 32" src="https://user-images.githubusercontent.com/98344909/156939983-76759fc7-d2f0-477d-babc-c8ed56eab9f6.png">
<img width="1557" alt="Screen Shot 2022-03-06 at 14 59 25" src="https://user-images.githubusercontent.com/98344909/156939984-9f606122-d9f6-499f-8736-3b402d5afb93.png">

**Comment by YingzhuoYang** [comment]
<img width="1231" alt="Screen Shot 2022-03-27 at 22 55 35" src="https://user-images.githubusercontent.com/98344909/160318835-7f37cd8c-3bc7-420b-bff0-2383c9840aef.png">
<img width="1231" alt="Screen Shot 2022-03-27 at 22 55 32" src="https://user-images.githubusercontent.com/98344909/160318839-3cd516ca-1089-48e6-b256-086e47a6bf2a.png">
<img width="1231" alt="Screen Shot 2022-03-27 at 22 55 29" src="https://user-images.githubusercontent.com/98344909/160318841-90e31606-a837-4121-ab74-94f6fefe5f5b.png">
<img width="1231" alt="Screen Shot 2022-03-27 at 22 55 26" src="https://user-images.githubusercontent.com/98344909/160318843-4cc9340d-ea61-417b-8843-4c04be78de4f.png">

**Comment by YingzhuoYang** [comment]
<img width="1233" alt="Screen Shot 2022-04-18 at 19 26 25" src="https://user-images.githubusercontent.com/98344909/163892488-600bb5ad-eddc-4260-951e-d87e88bee57a.png">
<img width="1233" alt="Screen Shot 2022-04-18 at 19 26 20" src="https://user-images.githubusercontent.com/98344909/163892489-905ef21d-321c-4615-99fe-609dc6c3bf01.png">
<img width="1233" alt="Screen Shot 2022-04-18 at 19 26 14" src="https://user-images.githubusercontent.com/98344909/163892492-bbb1d908-de94-44c1-ba96-42bf4f7eb050.png">
<img width="1233" alt="Screen Shot 2022-04-18 at 19 26 11" src="https://user-images.githubusercontent.com/98344909/163892494-fc118579-4843-4b5f-aa63-649a40120852.png">
