### ISSUE TITLE
get feedback on personas

### ISSUE THREAD

**Issue by JerryWuZiJie** [JerryWuZiJie/go_to_bed#44]

**Comment by ffund** [comment]
@JerryWuZiJie I can't work on this until you create the personas! Mention me with `@ffund` in a comment when you have those ready for me to review.

**Comment by ffund** [comment]
@YingzhuoYang Where is the affinity map, that shows how you organized the user research into a few different "axes" on which to place personas? I see some user research in #41 but it's not organized into those affinity maps. And then of course, I can't see where the personas in #43 fall on those "axes".

**Comment by YingzhuoYang** [comment]
Hi professor @ffund, the affinity map is in #42 which I also attached on this comment. 
<img width="1557" alt="Screen Shot 2022-03-06 at 14 57 49" src="https://user-images.githubusercontent.com/98344909/157059826-bddcae4e-bf31-456e-b05e-da6f252bbda6.png">

**Comment by ffund** [comment]
@YingzhuoYang I think it would help for you to review the user research, affinity map, and personas with the rest of your team @JerryWuZiJie before you get my review. thanks :)

**Comment by YingzhuoYang** [comment]
@ffund Please check the revised personas
