### ISSUE TITLE
Set up Project

### ISSUE THREAD

**Issue by YingzhuoYang** [JerryWuZiJie/go_to_bed#5]
- [x] Create Project
- [x] Add collaborators
- [x] Configure status options
- [x] Set up workflows
- [x] Associate with repository
- [x] Configure views

**Comment by YingzhuoYang** [comment]
@ffund Please review our project!

**Comment by ffund** [comment]
@YingzhuoYang please add me as a collaborator on your project so that I have edit permissions there :)

**Comment by ffund** [comment]
I cannot review this because I haven't been added as a collaborator on the project (Project > Settings > Manage Access).

**Comment by JerryWuZiJie** [comment]
@ffund I just change the project permission from "read" to "Admin", could you try again, please?

**Comment by ffund** [comment]
@JerryWuZiJie Looks good, thanks.
