### ISSUE TITLE
Write Background section of report

### ISSUE THREAD

**Issue by JerryWuZiJie** [JerryWuZiJie/go_to_bed#8]
Include followings:
- [x] the project motivation
- [x] user-research indicating a need
- [x] benefits and limitations of existing alternatives

Remark:
apply engineering design to produce solutions that meet specified needs with consideration of public health, safety, & welfare, as well as global, cultural, social, environmental, & economic factors
recognize ethical & professional responsibilities in engineering situations & make informed judgments, which consider the impact of engineering solutions in global, economic, environmental, & societal contexts

**Comment by JerryWuZiJie** [comment]
checked

**Comment by YingzhuoYang** [comment]
Completed writing the Background section of the report.
https://docs.google.com/document/d/1cRgLtwa4frtZ_yciSRpZw53O9PJ7il5CS3-KFaFuV6g/edit#
